services:
  - type: web
    name: lawfort-frontend
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NPM_CONFIG_PRODUCTION
        value: false
    staticPublishPath: ./dist