services:
  - type: web
    name: legal-logs-backend
    env: python
    buildCommand: |
      apt-get update && apt-get install -y poppler-utils
      pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn.conf.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: 1
      # Add your database environment variables here
      - key: DB_HOST
        value: mysql-1c58266a-prabhjotjaswal08-77ed.e.aivencloud.com
      - key: DB_PORT
        value: 14544
      - key: DB_USER
        value: avnadmin
      - key: DB_PASSWORD
        value: AVNS_IJYG8aEFX5D0ugOuMng
      - key: DB_NAME
        value: defaultdb
      - key: SECRET_KEY
        value: pabbo@123
      - key: FRONTEND_URL
        value: https://legal-logs.onrender.com
      - key: GROQ_API_KEY
        value: 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
